trees:
  OAK_LOG:
    leaves: OAK_LEAVES
    leaves-size: 3
    limit: 192
  BIRCH_LOG:
    leaves: BIRCH_LEAVES
    leaves-size: 3
    limit: 192
  SPRUCE_LOG:
    leaves: SPRUCE_LEAVES
    leaves-size: 3
    limit: 256
  JUNGLE_LOG:
    leaves: JUNGLE_LEAVES
    leaves-size: 4
    limit: 256
  ACACIA_LOG:
    leaves: ACACIA_LEAVES
    leaves-size: 4
    limit: 192
  DARK_OAK_LOG:
    leaves: DARK_OAK_LEAVES
    leaves-size: 4
    limit: 192
  WARPED_STEM:
    leaves: WARPED_WART_BLOCK
    leaves-size: 3
    limit: 192

axes:
  - WOODEN_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE
